### ISSUE TITLE
403 on events api

### ISSUE THREAD

**Issue by splisson** [splisson/devopstic#1]
Hello Sebastien.

First let me thank you by the devopstic project, I think you built a great tool.
I'm trying to adapt it to my bussiness case, and with some configurations i was able to connect with Github webhooks but I'm having some issues calling "/events" that is always returning
{
    "code": 403,
    "message": "you don't have permission to access this resource"
}

I have been stuck on this, and i was wonderin if you could give me a clue about wath is happening there.

I will be greatful with you help, or any clue there.

thanks

**Comment by splisson** [comment]
/events API is using there regular authentication middleware. It currently relies on a JWT token.
In order to get a JWT you currently have to use the login API with username and password: POST /tokens
See https://github.com/splisson/devopstic/blob/master/doc/usage.md

The username and password are defined in environment variables of where your run the api server: DEVOPSTIC_USERNAME and DEVOPSTIC_PASSWORD

Then you use the JWT in header:
```
Authorization: Bearer <JWT obtained from POST /tokens api>
```

**Comment by juanjopb** [comment]
Thanks @splisson by your answer.
That's exactly what I'm trying. Get the token(Works), but when im going to save an event, i got permissions error, even trying to xget the events.
I'm Using the last Imaged found splisson/devopstic:v0.4.2, saving github events works fine.
![Screenshot 2020-12-14 092118](https://user-images.githubusercontent.com/44626438/102092189-c9f8c780-3ded-11eb-8402-71d59100bee8.png)


`➜  ~ curl -XPOST http://localhost:8080/tokens -H "Content-Type: application/json" -d '{"username":"admin","password":"admin"}'
{"code":200,"expire":"2021-12-14T14:14:07Z","token":"eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mzk0OTEyNDcsImlkIjoiYWRtaW4iLCJvcmlnX2lhdCI6MTYwNzk1NTI0N30._f4olFMuDT9LM_h94arEr6jYHjvIMKSXNGXUSExKmq8"}%
➜  ~ curl -XPOST http://localhost:8080/events -H "Content-Type: application/json" -H "Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJleHAiOjE2Mzk0OTEyNDcsImlkIjoiYWRtaW4iLCJvcmlnX2lhdCI6MTYwNzk1NTI0N30._f4olFMuDT9LM_h94arEr6jYHjvIMKSXNGXUSExKmq8" -d "{"type":"commit","pipeline_id":"api","environment":"dev","commit_id":"1un1queid","status":"success","timestamp
":1561003507}"
{"code":403,"message":"you don't have permission to access this resource"}`

Thanks again for your help

**Comment by juanjopb** [comment]
Hello @splisson @splisson-altair 
I have been debugging, and I found in the middleware/jwt.go in line 61, when I change it the return false to true, the event works and is saved on the Database, 
Seems that "**data.(string)**" is returning _nil_ and the validation is not working, but I don't know which value should be there.

https://github.com/splisson/devopstic/blob/98e4d9e3284a556b746354e1c0a34178dde6b56b/middleware/jwt.go#L57-L63

Could you help me to check this??, Thanks!

**Comment by splisson** [comment]
DEVOPSTIC_USERNAME env variable should be set in the server environment.

Same for password. 
Then a call to token api should return a JWT for that user when
providing username and password in payload

Then that jwt should identify the user as being the adminUsername 

Authorizator data should contain  that username decoded from JWT

On December 29, 2020, Tim Jacomb <notifications@github.com> wrote:
> Hello @splisson <https://github.com/splisson>
> @splisson-altair <https://github.com/splisson-altair>
>  I have been debugging, and I found in the middleware/jwt.go in line

> 61, when I change it the return false to true, the event works and is

> saved on the Database,
>  Seems that "data.(string)" is returning nil and the validation is not

> working, but I don't know which value should be there.
>
> <https://github.com/splisson/devopstic/blob/98e4d9e3284a556b746354e1c0a34178dde6b56b/middleware/jwt.go#L57-
> L63>
>
> Could you help me to check this??, Thanks!
>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/splisson/devopstic/issues/1#issuecomment-752254252>,

or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AABAWAMCIVGOS5GS33WCL63SXJF3LANCNFSM4UVLL6LA>.

**Comment by juanjopb** [comment]
I have this on the variables 
I just Add "**DEVOPSTIC_USERNAME=admin**" because i was using only the following values

DEVOPSTIC_USER=admin
DEVOPSTIC_PASSWORD=devopstic
DEVOPSTIC_DATABASE_HOST=localhost
DEVOPSTIC_DATABASE_PORT=5432
DEVOPSTIC_DATABASE_NAME=postgres
DEVOPSTIC_GITHUB_WEBHOOK_SECRET=Dev0sptic
DEVOPSTIC_DATABASE_USERNAME=postgres
DEVOPSTIC_DATABASE_PASSWORD=password123
But still not working :\ .It's something special that i have to set? it's any specific value ??

**Comment by splisson** [comment]
That should work. I ll look at it when I m back tomorrow or the day
after

On December 29, 2020, Tim Jacomb <notifications@github.com> wrote:
> I have this on the variables
>  I just Add "DEVOPSTIC_USERNAME=admin" because i was using only the
> following values
>
> DEVOPSTIC_USER=admin
>  DEVOPSTIC_PASSWORD=devopstic
>  DEVOPSTIC_DATABASE_HOST=localhost
>  DEVOPSTIC_DATABASE_PORT=5432
>  DEVOPSTIC_DATABASE_NAME=postgres
>  DEVOPSTIC_GITHUB_WEBHOOK_SECRET=Dev0sptic
>  DEVOPSTIC_DATABASE_USERNAME=postgres
>  DEVOPSTIC_DATABASE_PASSWORD=password123
>
> It's something special that i have to set? it's any specific value ??

>

—
You are receiving this because you were mentioned.
Reply to this email directly, view it on GitHub
<https://github.com/splisson/devopstic/issues/1#issuecomment-752265779>,

or unsubscribe <https://github.com/notifications/unsubscribe-
auth/AABAWAK7E3443RUM5LXIDNTSXJLH7ANCNFSM4UVLL6LA>.

**Comment by splisson** [comment]
It seems the jwt library has changed a little, see
<https://github.com/appleboy/gin-jwt> and use the example to fix the
current devopstic code. I ll have a look when I m back at my computer

**Comment by splisson** [comment]
The code has been updated to use the latest version of https://github.com/appleboy/gin-jwt properly.
It should work now

**Comment by nhat-tong** [comment]
@splisson: thanks for your fantastic work. I tried to run this api with the latest version v0.4.2 but the same error came back.

Version: v0.4.2

Env variables:
DEVOPSTIC_USER=admin
DEVOPSTIC_PASSWORD=devopstic

POST /tokens: it worked. The jwt token is returned.

GET /commits (/events...) (Authorization: Bearer [jwt_token])
{
    "code": 403,
    "message": "you don't have permission to access this resource"
}

The the jwt library seems to be updated.
`
Authorizator: func(data interface{}, c *gin.Context) bool {
			// log.Printf("authorize %s", data)
			if v, ok := data.(*entities.User); ok && v.Username == adminUsername {
				return true
			}

			return false
		},
`
Thanks in advance,
